### ISSUE TITLE
Verbiage of Open Source OS feature

### ISSUE THREAD

**Issue by talta** [SynapticCelerity/contracts-solidity#1]
Within the features, change the verbiage of Open Source OS to be a bit clearer

This is why Dgramz only uses open source operating systems and on mobiles Android is by far the most in use.

Therefore, Dgramz prioritizes open source operating systems, for which the highest mobile adoption is Android.

**Comment by objectorange** [comment]
These needs moved to dgramz-marketing repo.

**Comment by talta** [comment]
moving to dgramz-marketing
